FROM debian:buster-20190910
LABEL maintainer="bbelovic@gmail.com"
RUN groupadd -r -g 2200 example && \
    useradd -rM -g example -u 2200 example
ENV APPROOT="/app" \
    APP="mailer.sh" \
    VERSION="0.1"
LABEL base.name="Mailer archetype" \
      base.version="${VERSION}"
WORKDIR $APPROOT
ADD . $APPROOT
ENTRYPOINT [ "/app/mailer.sh" ]
EXPOSE 33333
USER example:example